ARG ROS_DISTRO=lyrical
FROM ros:${ROS_DISTRO}-ros-base
ARG USERNAME=rosdev
ARG USER_UID=1000
ARG USER_GID=1000
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends     sudo git nano curl dbus-x11 xfce4 xfce4-terminal tigervnc-standalone-server novnc websockify     python3-colcon-common-extensions python3-rosdep     ros-${ROS_DISTRO}-rviz2 ros-${ROS_DISTRO}-sensor-msgs ros-${ROS_DISTRO}-geometry-msgs ros-${ROS_DISTRO}-tf2-ros     && rm -rf /var/lib/apt/lists/*     && groupadd --gid ${USER_GID} ${USERNAME}     && useradd --uid ${USER_UID} --gid ${USER_GID} -m ${USERNAME}     && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/${USERNAME}     && chmod 0440 /etc/sudoers.d/${USERNAME}
COPY docker/entrypoint.sh /usr/local/bin/ros-entrypoint.sh
COPY docker/start-desktop.sh /usr/local/bin/start-desktop.sh
COPY docker/vnc-xstartup /usr/local/bin/vnc-xstartup
RUN chmod +x /usr/local/bin/*.sh /usr/local/bin/vnc-xstartup
USER ${USERNAME}
WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/ros-entrypoint.sh"]
CMD ["/usr/local/bin/start-desktop.sh"]
