services:
  fake_lidar:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-lyrical}
    network_mode: host
    ipc: host
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-42}
    command: ros2 run docker_ros2_lab fake_lidar
  monitor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: ${ROS_DISTRO:-lyrical}
    network_mode: host
    ipc: host
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-42}
    command: ros2 run docker_ros2_lab scan_monitor
